name: Deploy to Local IIS

on:
  push:
    branches:
      - master

jobs:
    
  deploy-web-2-0:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      
    - name: Build Solution
      run: msbuild code/Web_2_0/Web_2_0/Web_2_0.csproj /p:Configuration=Release /t:Build /p:OutDir="C:\Output\" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true