name: Deploy to Local IIS

on:
  push:
    branches:
      - master

jobs:
  deploy-web-2-0:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build Web_2.0 Solution
      run: "C:\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe code/Web_2.0/Web_2.0.sln /p:Configuration=Release" 
    - name: Deploy to Local IIS
      run: msdeploy.exe -verb:sync -source:contentPath="code/Web_2.0" -dest:contentPath="IIS://localhost/w3svc/1",ComputerName="localhost" -allowUntrusted
      env:
        MSDeployPath: "C:\Program Files\\IIS\\Microsoft Web Deploy V3\\msdeploy.exe" # Adjust path as needed